/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.contracts.v1.BuilderConfig');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.contracts.v1.BuildParamsConfig');
goog.require('proto.contracts.v1.BuildVersionConfig');
goog.require('proto.contracts.v1.CIServerConfig');
goog.require('proto.contracts.v1.CredentialConfig');
goog.require('proto.contracts.v1.GitConfig');
goog.require('proto.contracts.v1.ReleaseParamsConfig');
goog.require('proto.contracts.v1.TrustedImageConfig');
goog.require('proto.manifest.v1.EstafetteEvent');
goog.require('proto.manifest.v1.EstafetteManifest');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contracts.v1.BuilderConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.contracts.v1.BuilderConfig.repeatedFields_, null);
};
goog.inherits(proto.contracts.v1.BuilderConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.contracts.v1.BuilderConfig.displayName = 'proto.contracts.v1.BuilderConfig';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.contracts.v1.BuilderConfig.repeatedFields_ = [8,14,15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contracts.v1.BuilderConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.contracts.v1.BuilderConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contracts.v1.BuilderConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.BuilderConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, ""),
    track: jspb.Message.getFieldWithDefault(msg, 2, ""),
    registryMirror: jspb.Message.getFieldWithDefault(msg, 3, ""),
    dockerDaemonMtu: jspb.Message.getFieldWithDefault(msg, 4, ""),
    manifest: (f = msg.getManifest()) && proto.manifest.v1.EstafetteManifest.toObject(includeInstance, f),
    jobName: jspb.Message.getFieldWithDefault(msg, 6, ""),
    releaseName: jspb.Message.getFieldWithDefault(msg, 7, ""),
    eventsList: jspb.Message.toObjectList(msg.getEventsList(),
    proto.manifest.v1.EstafetteEvent.toObject, includeInstance),
    ciServer: (f = msg.getCiServer()) && proto.contracts.v1.CIServerConfig.toObject(includeInstance, f),
    buildParams: (f = msg.getBuildParams()) && proto.contracts.v1.BuildParamsConfig.toObject(includeInstance, f),
    releaseParams: (f = msg.getReleaseParams()) && proto.contracts.v1.ReleaseParamsConfig.toObject(includeInstance, f),
    git: (f = msg.getGit()) && proto.contracts.v1.GitConfig.toObject(includeInstance, f),
    buildVersion: (f = msg.getBuildVersion()) && proto.contracts.v1.BuildVersionConfig.toObject(includeInstance, f),
    credentialsList: jspb.Message.toObjectList(msg.getCredentialsList(),
    proto.contracts.v1.CredentialConfig.toObject, includeInstance),
    trustedImagesList: jspb.Message.toObjectList(msg.getTrustedImagesList(),
    proto.contracts.v1.TrustedImageConfig.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contracts.v1.BuilderConfig}
 */
proto.contracts.v1.BuilderConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contracts.v1.BuilderConfig;
  return proto.contracts.v1.BuilderConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contracts.v1.BuilderConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contracts.v1.BuilderConfig}
 */
proto.contracts.v1.BuilderConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrack(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRegistryMirror(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDockerDaemonMtu(value);
      break;
    case 5:
      var value = new proto.manifest.v1.EstafetteManifest;
      reader.readMessage(value,proto.manifest.v1.EstafetteManifest.deserializeBinaryFromReader);
      msg.setManifest(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setReleaseName(value);
      break;
    case 8:
      var value = new proto.manifest.v1.EstafetteEvent;
      reader.readMessage(value,proto.manifest.v1.EstafetteEvent.deserializeBinaryFromReader);
      msg.addEvents(value);
      break;
    case 9:
      var value = new proto.contracts.v1.CIServerConfig;
      reader.readMessage(value,proto.contracts.v1.CIServerConfig.deserializeBinaryFromReader);
      msg.setCiServer(value);
      break;
    case 10:
      var value = new proto.contracts.v1.BuildParamsConfig;
      reader.readMessage(value,proto.contracts.v1.BuildParamsConfig.deserializeBinaryFromReader);
      msg.setBuildParams(value);
      break;
    case 11:
      var value = new proto.contracts.v1.ReleaseParamsConfig;
      reader.readMessage(value,proto.contracts.v1.ReleaseParamsConfig.deserializeBinaryFromReader);
      msg.setReleaseParams(value);
      break;
    case 12:
      var value = new proto.contracts.v1.GitConfig;
      reader.readMessage(value,proto.contracts.v1.GitConfig.deserializeBinaryFromReader);
      msg.setGit(value);
      break;
    case 13:
      var value = new proto.contracts.v1.BuildVersionConfig;
      reader.readMessage(value,proto.contracts.v1.BuildVersionConfig.deserializeBinaryFromReader);
      msg.setBuildVersion(value);
      break;
    case 14:
      var value = new proto.contracts.v1.CredentialConfig;
      reader.readMessage(value,proto.contracts.v1.CredentialConfig.deserializeBinaryFromReader);
      msg.addCredentials(value);
      break;
    case 15:
      var value = new proto.contracts.v1.TrustedImageConfig;
      reader.readMessage(value,proto.contracts.v1.TrustedImageConfig.deserializeBinaryFromReader);
      msg.addTrustedImages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contracts.v1.BuilderConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contracts.v1.BuilderConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contracts.v1.BuilderConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.BuilderConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAction();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTrack();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRegistryMirror();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDockerDaemonMtu();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getManifest();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.manifest.v1.EstafetteManifest.serializeBinaryToWriter
    );
  }
  f = message.getJobName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getReleaseName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getEventsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.manifest.v1.EstafetteEvent.serializeBinaryToWriter
    );
  }
  f = message.getCiServer();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.contracts.v1.CIServerConfig.serializeBinaryToWriter
    );
  }
  f = message.getBuildParams();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.contracts.v1.BuildParamsConfig.serializeBinaryToWriter
    );
  }
  f = message.getReleaseParams();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.contracts.v1.ReleaseParamsConfig.serializeBinaryToWriter
    );
  }
  f = message.getGit();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.contracts.v1.GitConfig.serializeBinaryToWriter
    );
  }
  f = message.getBuildVersion();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto.contracts.v1.BuildVersionConfig.serializeBinaryToWriter
    );
  }
  f = message.getCredentialsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      proto.contracts.v1.CredentialConfig.serializeBinaryToWriter
    );
  }
  f = message.getTrustedImagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      proto.contracts.v1.TrustedImageConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional string action = 1;
 * @return {string}
 */
proto.contracts.v1.BuilderConfig.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.contracts.v1.BuilderConfig.prototype.setAction = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string track = 2;
 * @return {string}
 */
proto.contracts.v1.BuilderConfig.prototype.getTrack = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.contracts.v1.BuilderConfig.prototype.setTrack = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string registry_mirror = 3;
 * @return {string}
 */
proto.contracts.v1.BuilderConfig.prototype.getRegistryMirror = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.contracts.v1.BuilderConfig.prototype.setRegistryMirror = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string docker_daemon_mtu = 4;
 * @return {string}
 */
proto.contracts.v1.BuilderConfig.prototype.getDockerDaemonMtu = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.contracts.v1.BuilderConfig.prototype.setDockerDaemonMtu = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional manifest.v1.EstafetteManifest manifest = 5;
 * @return {?proto.manifest.v1.EstafetteManifest}
 */
proto.contracts.v1.BuilderConfig.prototype.getManifest = function() {
  return /** @type{?proto.manifest.v1.EstafetteManifest} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteManifest, 5));
};


/** @param {?proto.manifest.v1.EstafetteManifest|undefined} value */
proto.contracts.v1.BuilderConfig.prototype.setManifest = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.contracts.v1.BuilderConfig.prototype.clearManifest = function() {
  this.setManifest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.BuilderConfig.prototype.hasManifest = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string job_name = 6;
 * @return {string}
 */
proto.contracts.v1.BuilderConfig.prototype.getJobName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.contracts.v1.BuilderConfig.prototype.setJobName = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string release_name = 7;
 * @return {string}
 */
proto.contracts.v1.BuilderConfig.prototype.getReleaseName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.contracts.v1.BuilderConfig.prototype.setReleaseName = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated manifest.v1.EstafetteEvent events = 8;
 * @return {!Array<!proto.manifest.v1.EstafetteEvent>}
 */
proto.contracts.v1.BuilderConfig.prototype.getEventsList = function() {
  return /** @type{!Array<!proto.manifest.v1.EstafetteEvent>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.manifest.v1.EstafetteEvent, 8));
};


/** @param {!Array<!proto.manifest.v1.EstafetteEvent>} value */
proto.contracts.v1.BuilderConfig.prototype.setEventsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.manifest.v1.EstafetteEvent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.manifest.v1.EstafetteEvent}
 */
proto.contracts.v1.BuilderConfig.prototype.addEvents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.manifest.v1.EstafetteEvent, opt_index);
};


proto.contracts.v1.BuilderConfig.prototype.clearEventsList = function() {
  this.setEventsList([]);
};


/**
 * optional CIServerConfig ci_server = 9;
 * @return {?proto.contracts.v1.CIServerConfig}
 */
proto.contracts.v1.BuilderConfig.prototype.getCiServer = function() {
  return /** @type{?proto.contracts.v1.CIServerConfig} */ (
    jspb.Message.getWrapperField(this, proto.contracts.v1.CIServerConfig, 9));
};


/** @param {?proto.contracts.v1.CIServerConfig|undefined} value */
proto.contracts.v1.BuilderConfig.prototype.setCiServer = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.contracts.v1.BuilderConfig.prototype.clearCiServer = function() {
  this.setCiServer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.BuilderConfig.prototype.hasCiServer = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional BuildParamsConfig build_params = 10;
 * @return {?proto.contracts.v1.BuildParamsConfig}
 */
proto.contracts.v1.BuilderConfig.prototype.getBuildParams = function() {
  return /** @type{?proto.contracts.v1.BuildParamsConfig} */ (
    jspb.Message.getWrapperField(this, proto.contracts.v1.BuildParamsConfig, 10));
};


/** @param {?proto.contracts.v1.BuildParamsConfig|undefined} value */
proto.contracts.v1.BuilderConfig.prototype.setBuildParams = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.contracts.v1.BuilderConfig.prototype.clearBuildParams = function() {
  this.setBuildParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.BuilderConfig.prototype.hasBuildParams = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional ReleaseParamsConfig release_params = 11;
 * @return {?proto.contracts.v1.ReleaseParamsConfig}
 */
proto.contracts.v1.BuilderConfig.prototype.getReleaseParams = function() {
  return /** @type{?proto.contracts.v1.ReleaseParamsConfig} */ (
    jspb.Message.getWrapperField(this, proto.contracts.v1.ReleaseParamsConfig, 11));
};


/** @param {?proto.contracts.v1.ReleaseParamsConfig|undefined} value */
proto.contracts.v1.BuilderConfig.prototype.setReleaseParams = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.contracts.v1.BuilderConfig.prototype.clearReleaseParams = function() {
  this.setReleaseParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.BuilderConfig.prototype.hasReleaseParams = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional GitConfig git = 12;
 * @return {?proto.contracts.v1.GitConfig}
 */
proto.contracts.v1.BuilderConfig.prototype.getGit = function() {
  return /** @type{?proto.contracts.v1.GitConfig} */ (
    jspb.Message.getWrapperField(this, proto.contracts.v1.GitConfig, 12));
};


/** @param {?proto.contracts.v1.GitConfig|undefined} value */
proto.contracts.v1.BuilderConfig.prototype.setGit = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.contracts.v1.BuilderConfig.prototype.clearGit = function() {
  this.setGit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.BuilderConfig.prototype.hasGit = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional BuildVersionConfig build_version = 13;
 * @return {?proto.contracts.v1.BuildVersionConfig}
 */
proto.contracts.v1.BuilderConfig.prototype.getBuildVersion = function() {
  return /** @type{?proto.contracts.v1.BuildVersionConfig} */ (
    jspb.Message.getWrapperField(this, proto.contracts.v1.BuildVersionConfig, 13));
};


/** @param {?proto.contracts.v1.BuildVersionConfig|undefined} value */
proto.contracts.v1.BuilderConfig.prototype.setBuildVersion = function(value) {
  jspb.Message.setWrapperField(this, 13, value);
};


proto.contracts.v1.BuilderConfig.prototype.clearBuildVersion = function() {
  this.setBuildVersion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.BuilderConfig.prototype.hasBuildVersion = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * repeated CredentialConfig credentials = 14;
 * @return {!Array<!proto.contracts.v1.CredentialConfig>}
 */
proto.contracts.v1.BuilderConfig.prototype.getCredentialsList = function() {
  return /** @type{!Array<!proto.contracts.v1.CredentialConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.contracts.v1.CredentialConfig, 14));
};


/** @param {!Array<!proto.contracts.v1.CredentialConfig>} value */
proto.contracts.v1.BuilderConfig.prototype.setCredentialsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.contracts.v1.CredentialConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.contracts.v1.CredentialConfig}
 */
proto.contracts.v1.BuilderConfig.prototype.addCredentials = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.contracts.v1.CredentialConfig, opt_index);
};


proto.contracts.v1.BuilderConfig.prototype.clearCredentialsList = function() {
  this.setCredentialsList([]);
};


/**
 * repeated TrustedImageConfig trusted_images = 15;
 * @return {!Array<!proto.contracts.v1.TrustedImageConfig>}
 */
proto.contracts.v1.BuilderConfig.prototype.getTrustedImagesList = function() {
  return /** @type{!Array<!proto.contracts.v1.TrustedImageConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.contracts.v1.TrustedImageConfig, 15));
};


/** @param {!Array<!proto.contracts.v1.TrustedImageConfig>} value */
proto.contracts.v1.BuilderConfig.prototype.setTrustedImagesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.contracts.v1.TrustedImageConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.contracts.v1.TrustedImageConfig}
 */
proto.contracts.v1.BuilderConfig.prototype.addTrustedImages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.contracts.v1.TrustedImageConfig, opt_index);
};


proto.contracts.v1.BuilderConfig.prototype.clearTrustedImagesList = function() {
  this.setTrustedImagesList([]);
};


