/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.manifest.v1.EstafetteTrigger');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.manifest.v1.EstafetteCronTrigger');
goog.require('proto.manifest.v1.EstafetteDockerTrigger');
goog.require('proto.manifest.v1.EstafetteGitTrigger');
goog.require('proto.manifest.v1.EstafettePipelineTrigger');
goog.require('proto.manifest.v1.EstafettePubSubTrigger');
goog.require('proto.manifest.v1.EstafetteReleaseTrigger');
goog.require('proto.manifest.v1.EstafetteTriggerBuildAction');
goog.require('proto.manifest.v1.EstafetteTriggerReleaseAction');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.manifest.v1.EstafetteTrigger = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.manifest.v1.EstafetteTrigger, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.manifest.v1.EstafetteTrigger.displayName = 'proto.manifest.v1.EstafetteTrigger';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.manifest.v1.EstafetteTrigger.prototype.toObject = function(opt_includeInstance) {
  return proto.manifest.v1.EstafetteTrigger.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.manifest.v1.EstafetteTrigger} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manifest.v1.EstafetteTrigger.toObject = function(includeInstance, msg) {
  var f, obj = {
    pipeline: (f = msg.getPipeline()) && proto.manifest.v1.EstafettePipelineTrigger.toObject(includeInstance, f),
    release: (f = msg.getRelease()) && proto.manifest.v1.EstafetteReleaseTrigger.toObject(includeInstance, f),
    git: (f = msg.getGit()) && proto.manifest.v1.EstafetteGitTrigger.toObject(includeInstance, f),
    docker: (f = msg.getDocker()) && proto.manifest.v1.EstafetteDockerTrigger.toObject(includeInstance, f),
    cron: (f = msg.getCron()) && proto.manifest.v1.EstafetteCronTrigger.toObject(includeInstance, f),
    pubSub: (f = msg.getPubSub()) && proto.manifest.v1.EstafettePubSubTrigger.toObject(includeInstance, f),
    buildAction: (f = msg.getBuildAction()) && proto.manifest.v1.EstafetteTriggerBuildAction.toObject(includeInstance, f),
    releaseAction: (f = msg.getReleaseAction()) && proto.manifest.v1.EstafetteTriggerReleaseAction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.manifest.v1.EstafetteTrigger}
 */
proto.manifest.v1.EstafetteTrigger.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.manifest.v1.EstafetteTrigger;
  return proto.manifest.v1.EstafetteTrigger.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.manifest.v1.EstafetteTrigger} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.manifest.v1.EstafetteTrigger}
 */
proto.manifest.v1.EstafetteTrigger.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.manifest.v1.EstafettePipelineTrigger;
      reader.readMessage(value,proto.manifest.v1.EstafettePipelineTrigger.deserializeBinaryFromReader);
      msg.setPipeline(value);
      break;
    case 2:
      var value = new proto.manifest.v1.EstafetteReleaseTrigger;
      reader.readMessage(value,proto.manifest.v1.EstafetteReleaseTrigger.deserializeBinaryFromReader);
      msg.setRelease(value);
      break;
    case 3:
      var value = new proto.manifest.v1.EstafetteGitTrigger;
      reader.readMessage(value,proto.manifest.v1.EstafetteGitTrigger.deserializeBinaryFromReader);
      msg.setGit(value);
      break;
    case 4:
      var value = new proto.manifest.v1.EstafetteDockerTrigger;
      reader.readMessage(value,proto.manifest.v1.EstafetteDockerTrigger.deserializeBinaryFromReader);
      msg.setDocker(value);
      break;
    case 5:
      var value = new proto.manifest.v1.EstafetteCronTrigger;
      reader.readMessage(value,proto.manifest.v1.EstafetteCronTrigger.deserializeBinaryFromReader);
      msg.setCron(value);
      break;
    case 6:
      var value = new proto.manifest.v1.EstafettePubSubTrigger;
      reader.readMessage(value,proto.manifest.v1.EstafettePubSubTrigger.deserializeBinaryFromReader);
      msg.setPubSub(value);
      break;
    case 7:
      var value = new proto.manifest.v1.EstafetteTriggerBuildAction;
      reader.readMessage(value,proto.manifest.v1.EstafetteTriggerBuildAction.deserializeBinaryFromReader);
      msg.setBuildAction(value);
      break;
    case 8:
      var value = new proto.manifest.v1.EstafetteTriggerReleaseAction;
      reader.readMessage(value,proto.manifest.v1.EstafetteTriggerReleaseAction.deserializeBinaryFromReader);
      msg.setReleaseAction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.manifest.v1.EstafetteTrigger.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.manifest.v1.EstafetteTrigger.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.manifest.v1.EstafetteTrigger} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manifest.v1.EstafetteTrigger.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPipeline();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.manifest.v1.EstafettePipelineTrigger.serializeBinaryToWriter
    );
  }
  f = message.getRelease();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.manifest.v1.EstafetteReleaseTrigger.serializeBinaryToWriter
    );
  }
  f = message.getGit();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.manifest.v1.EstafetteGitTrigger.serializeBinaryToWriter
    );
  }
  f = message.getDocker();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.manifest.v1.EstafetteDockerTrigger.serializeBinaryToWriter
    );
  }
  f = message.getCron();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.manifest.v1.EstafetteCronTrigger.serializeBinaryToWriter
    );
  }
  f = message.getPubSub();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.manifest.v1.EstafettePubSubTrigger.serializeBinaryToWriter
    );
  }
  f = message.getBuildAction();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.manifest.v1.EstafetteTriggerBuildAction.serializeBinaryToWriter
    );
  }
  f = message.getReleaseAction();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.manifest.v1.EstafetteTriggerReleaseAction.serializeBinaryToWriter
    );
  }
};


/**
 * optional EstafettePipelineTrigger pipeline = 1;
 * @return {?proto.manifest.v1.EstafettePipelineTrigger}
 */
proto.manifest.v1.EstafetteTrigger.prototype.getPipeline = function() {
  return /** @type{?proto.manifest.v1.EstafettePipelineTrigger} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafettePipelineTrigger, 1));
};


/** @param {?proto.manifest.v1.EstafettePipelineTrigger|undefined} value */
proto.manifest.v1.EstafetteTrigger.prototype.setPipeline = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.manifest.v1.EstafetteTrigger.prototype.clearPipeline = function() {
  this.setPipeline(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteTrigger.prototype.hasPipeline = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional EstafetteReleaseTrigger release = 2;
 * @return {?proto.manifest.v1.EstafetteReleaseTrigger}
 */
proto.manifest.v1.EstafetteTrigger.prototype.getRelease = function() {
  return /** @type{?proto.manifest.v1.EstafetteReleaseTrigger} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteReleaseTrigger, 2));
};


/** @param {?proto.manifest.v1.EstafetteReleaseTrigger|undefined} value */
proto.manifest.v1.EstafetteTrigger.prototype.setRelease = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.manifest.v1.EstafetteTrigger.prototype.clearRelease = function() {
  this.setRelease(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteTrigger.prototype.hasRelease = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional EstafetteGitTrigger git = 3;
 * @return {?proto.manifest.v1.EstafetteGitTrigger}
 */
proto.manifest.v1.EstafetteTrigger.prototype.getGit = function() {
  return /** @type{?proto.manifest.v1.EstafetteGitTrigger} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteGitTrigger, 3));
};


/** @param {?proto.manifest.v1.EstafetteGitTrigger|undefined} value */
proto.manifest.v1.EstafetteTrigger.prototype.setGit = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.manifest.v1.EstafetteTrigger.prototype.clearGit = function() {
  this.setGit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteTrigger.prototype.hasGit = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional EstafetteDockerTrigger docker = 4;
 * @return {?proto.manifest.v1.EstafetteDockerTrigger}
 */
proto.manifest.v1.EstafetteTrigger.prototype.getDocker = function() {
  return /** @type{?proto.manifest.v1.EstafetteDockerTrigger} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteDockerTrigger, 4));
};


/** @param {?proto.manifest.v1.EstafetteDockerTrigger|undefined} value */
proto.manifest.v1.EstafetteTrigger.prototype.setDocker = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.manifest.v1.EstafetteTrigger.prototype.clearDocker = function() {
  this.setDocker(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteTrigger.prototype.hasDocker = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional EstafetteCronTrigger cron = 5;
 * @return {?proto.manifest.v1.EstafetteCronTrigger}
 */
proto.manifest.v1.EstafetteTrigger.prototype.getCron = function() {
  return /** @type{?proto.manifest.v1.EstafetteCronTrigger} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteCronTrigger, 5));
};


/** @param {?proto.manifest.v1.EstafetteCronTrigger|undefined} value */
proto.manifest.v1.EstafetteTrigger.prototype.setCron = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.manifest.v1.EstafetteTrigger.prototype.clearCron = function() {
  this.setCron(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteTrigger.prototype.hasCron = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional EstafettePubSubTrigger pub_sub = 6;
 * @return {?proto.manifest.v1.EstafettePubSubTrigger}
 */
proto.manifest.v1.EstafetteTrigger.prototype.getPubSub = function() {
  return /** @type{?proto.manifest.v1.EstafettePubSubTrigger} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafettePubSubTrigger, 6));
};


/** @param {?proto.manifest.v1.EstafettePubSubTrigger|undefined} value */
proto.manifest.v1.EstafetteTrigger.prototype.setPubSub = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.manifest.v1.EstafetteTrigger.prototype.clearPubSub = function() {
  this.setPubSub(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteTrigger.prototype.hasPubSub = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional EstafetteTriggerBuildAction build_action = 7;
 * @return {?proto.manifest.v1.EstafetteTriggerBuildAction}
 */
proto.manifest.v1.EstafetteTrigger.prototype.getBuildAction = function() {
  return /** @type{?proto.manifest.v1.EstafetteTriggerBuildAction} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteTriggerBuildAction, 7));
};


/** @param {?proto.manifest.v1.EstafetteTriggerBuildAction|undefined} value */
proto.manifest.v1.EstafetteTrigger.prototype.setBuildAction = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.manifest.v1.EstafetteTrigger.prototype.clearBuildAction = function() {
  this.setBuildAction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteTrigger.prototype.hasBuildAction = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional EstafetteTriggerReleaseAction release_action = 8;
 * @return {?proto.manifest.v1.EstafetteTriggerReleaseAction}
 */
proto.manifest.v1.EstafetteTrigger.prototype.getReleaseAction = function() {
  return /** @type{?proto.manifest.v1.EstafetteTriggerReleaseAction} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteTriggerReleaseAction, 8));
};


/** @param {?proto.manifest.v1.EstafetteTriggerReleaseAction|undefined} value */
proto.manifest.v1.EstafetteTrigger.prototype.setReleaseAction = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.manifest.v1.EstafetteTrigger.prototype.clearReleaseAction = function() {
  this.setReleaseAction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteTrigger.prototype.hasReleaseAction = function() {
  return jspb.Message.getField(this, 8) != null;
};


