/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.manifest.v1.EstafetteEvent');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.manifest.v1.EstafetteCronEvent');
goog.require('proto.manifest.v1.EstafetteDockerEvent');
goog.require('proto.manifest.v1.EstafetteGitEvent');
goog.require('proto.manifest.v1.EstafetteManualEvent');
goog.require('proto.manifest.v1.EstafettePipelineEvent');
goog.require('proto.manifest.v1.EstafettePubSubEvent');
goog.require('proto.manifest.v1.EstafetteReleaseEvent');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.manifest.v1.EstafetteEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.manifest.v1.EstafetteEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.manifest.v1.EstafetteEvent.displayName = 'proto.manifest.v1.EstafetteEvent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.manifest.v1.EstafetteEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.manifest.v1.EstafetteEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.manifest.v1.EstafetteEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manifest.v1.EstafetteEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    pipeline: (f = msg.getPipeline()) && proto.manifest.v1.EstafettePipelineEvent.toObject(includeInstance, f),
    release: (f = msg.getRelease()) && proto.manifest.v1.EstafetteReleaseEvent.toObject(includeInstance, f),
    git: (f = msg.getGit()) && proto.manifest.v1.EstafetteGitEvent.toObject(includeInstance, f),
    docker: (f = msg.getDocker()) && proto.manifest.v1.EstafetteDockerEvent.toObject(includeInstance, f),
    cron: (f = msg.getCron()) && proto.manifest.v1.EstafetteCronEvent.toObject(includeInstance, f),
    pubSub: (f = msg.getPubSub()) && proto.manifest.v1.EstafettePubSubEvent.toObject(includeInstance, f),
    manual: (f = msg.getManual()) && proto.manifest.v1.EstafetteManualEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.manifest.v1.EstafetteEvent}
 */
proto.manifest.v1.EstafetteEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.manifest.v1.EstafetteEvent;
  return proto.manifest.v1.EstafetteEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.manifest.v1.EstafetteEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.manifest.v1.EstafetteEvent}
 */
proto.manifest.v1.EstafetteEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.manifest.v1.EstafettePipelineEvent;
      reader.readMessage(value,proto.manifest.v1.EstafettePipelineEvent.deserializeBinaryFromReader);
      msg.setPipeline(value);
      break;
    case 2:
      var value = new proto.manifest.v1.EstafetteReleaseEvent;
      reader.readMessage(value,proto.manifest.v1.EstafetteReleaseEvent.deserializeBinaryFromReader);
      msg.setRelease(value);
      break;
    case 3:
      var value = new proto.manifest.v1.EstafetteGitEvent;
      reader.readMessage(value,proto.manifest.v1.EstafetteGitEvent.deserializeBinaryFromReader);
      msg.setGit(value);
      break;
    case 4:
      var value = new proto.manifest.v1.EstafetteDockerEvent;
      reader.readMessage(value,proto.manifest.v1.EstafetteDockerEvent.deserializeBinaryFromReader);
      msg.setDocker(value);
      break;
    case 5:
      var value = new proto.manifest.v1.EstafetteCronEvent;
      reader.readMessage(value,proto.manifest.v1.EstafetteCronEvent.deserializeBinaryFromReader);
      msg.setCron(value);
      break;
    case 6:
      var value = new proto.manifest.v1.EstafettePubSubEvent;
      reader.readMessage(value,proto.manifest.v1.EstafettePubSubEvent.deserializeBinaryFromReader);
      msg.setPubSub(value);
      break;
    case 7:
      var value = new proto.manifest.v1.EstafetteManualEvent;
      reader.readMessage(value,proto.manifest.v1.EstafetteManualEvent.deserializeBinaryFromReader);
      msg.setManual(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.manifest.v1.EstafetteEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.manifest.v1.EstafetteEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.manifest.v1.EstafetteEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manifest.v1.EstafetteEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPipeline();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.manifest.v1.EstafettePipelineEvent.serializeBinaryToWriter
    );
  }
  f = message.getRelease();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.manifest.v1.EstafetteReleaseEvent.serializeBinaryToWriter
    );
  }
  f = message.getGit();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.manifest.v1.EstafetteGitEvent.serializeBinaryToWriter
    );
  }
  f = message.getDocker();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.manifest.v1.EstafetteDockerEvent.serializeBinaryToWriter
    );
  }
  f = message.getCron();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.manifest.v1.EstafetteCronEvent.serializeBinaryToWriter
    );
  }
  f = message.getPubSub();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.manifest.v1.EstafettePubSubEvent.serializeBinaryToWriter
    );
  }
  f = message.getManual();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.manifest.v1.EstafetteManualEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional EstafettePipelineEvent pipeline = 1;
 * @return {?proto.manifest.v1.EstafettePipelineEvent}
 */
proto.manifest.v1.EstafetteEvent.prototype.getPipeline = function() {
  return /** @type{?proto.manifest.v1.EstafettePipelineEvent} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafettePipelineEvent, 1));
};


/** @param {?proto.manifest.v1.EstafettePipelineEvent|undefined} value */
proto.manifest.v1.EstafetteEvent.prototype.setPipeline = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.manifest.v1.EstafetteEvent.prototype.clearPipeline = function() {
  this.setPipeline(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteEvent.prototype.hasPipeline = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional EstafetteReleaseEvent release = 2;
 * @return {?proto.manifest.v1.EstafetteReleaseEvent}
 */
proto.manifest.v1.EstafetteEvent.prototype.getRelease = function() {
  return /** @type{?proto.manifest.v1.EstafetteReleaseEvent} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteReleaseEvent, 2));
};


/** @param {?proto.manifest.v1.EstafetteReleaseEvent|undefined} value */
proto.manifest.v1.EstafetteEvent.prototype.setRelease = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.manifest.v1.EstafetteEvent.prototype.clearRelease = function() {
  this.setRelease(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteEvent.prototype.hasRelease = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional EstafetteGitEvent git = 3;
 * @return {?proto.manifest.v1.EstafetteGitEvent}
 */
proto.manifest.v1.EstafetteEvent.prototype.getGit = function() {
  return /** @type{?proto.manifest.v1.EstafetteGitEvent} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteGitEvent, 3));
};


/** @param {?proto.manifest.v1.EstafetteGitEvent|undefined} value */
proto.manifest.v1.EstafetteEvent.prototype.setGit = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.manifest.v1.EstafetteEvent.prototype.clearGit = function() {
  this.setGit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteEvent.prototype.hasGit = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional EstafetteDockerEvent docker = 4;
 * @return {?proto.manifest.v1.EstafetteDockerEvent}
 */
proto.manifest.v1.EstafetteEvent.prototype.getDocker = function() {
  return /** @type{?proto.manifest.v1.EstafetteDockerEvent} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteDockerEvent, 4));
};


/** @param {?proto.manifest.v1.EstafetteDockerEvent|undefined} value */
proto.manifest.v1.EstafetteEvent.prototype.setDocker = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.manifest.v1.EstafetteEvent.prototype.clearDocker = function() {
  this.setDocker(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteEvent.prototype.hasDocker = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional EstafetteCronEvent cron = 5;
 * @return {?proto.manifest.v1.EstafetteCronEvent}
 */
proto.manifest.v1.EstafetteEvent.prototype.getCron = function() {
  return /** @type{?proto.manifest.v1.EstafetteCronEvent} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteCronEvent, 5));
};


/** @param {?proto.manifest.v1.EstafetteCronEvent|undefined} value */
proto.manifest.v1.EstafetteEvent.prototype.setCron = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.manifest.v1.EstafetteEvent.prototype.clearCron = function() {
  this.setCron(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteEvent.prototype.hasCron = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional EstafettePubSubEvent pub_sub = 6;
 * @return {?proto.manifest.v1.EstafettePubSubEvent}
 */
proto.manifest.v1.EstafetteEvent.prototype.getPubSub = function() {
  return /** @type{?proto.manifest.v1.EstafettePubSubEvent} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafettePubSubEvent, 6));
};


/** @param {?proto.manifest.v1.EstafettePubSubEvent|undefined} value */
proto.manifest.v1.EstafetteEvent.prototype.setPubSub = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.manifest.v1.EstafetteEvent.prototype.clearPubSub = function() {
  this.setPubSub(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteEvent.prototype.hasPubSub = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional EstafetteManualEvent manual = 7;
 * @return {?proto.manifest.v1.EstafetteManualEvent}
 */
proto.manifest.v1.EstafetteEvent.prototype.getManual = function() {
  return /** @type{?proto.manifest.v1.EstafetteManualEvent} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteManualEvent, 7));
};


/** @param {?proto.manifest.v1.EstafetteManualEvent|undefined} value */
proto.manifest.v1.EstafetteEvent.prototype.setManual = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.manifest.v1.EstafetteEvent.prototype.clearManual = function() {
  this.setManual(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteEvent.prototype.hasManual = function() {
  return jspb.Message.getField(this, 7) != null;
};


