/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.manifest.v1.EstafetteReleaseEvent');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.manifest.v1.EstafetteReleaseEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.manifest.v1.EstafetteReleaseEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.manifest.v1.EstafetteReleaseEvent.displayName = 'proto.manifest.v1.EstafetteReleaseEvent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.manifest.v1.EstafetteReleaseEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.manifest.v1.EstafetteReleaseEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.manifest.v1.EstafetteReleaseEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manifest.v1.EstafetteReleaseEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    releaseVersion: jspb.Message.getFieldWithDefault(msg, 1, ""),
    repoSource: jspb.Message.getFieldWithDefault(msg, 2, ""),
    repoOwner: jspb.Message.getFieldWithDefault(msg, 3, ""),
    repoName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    target: jspb.Message.getFieldWithDefault(msg, 5, ""),
    status: jspb.Message.getFieldWithDefault(msg, 6, ""),
    event: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.manifest.v1.EstafetteReleaseEvent}
 */
proto.manifest.v1.EstafetteReleaseEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.manifest.v1.EstafetteReleaseEvent;
  return proto.manifest.v1.EstafetteReleaseEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.manifest.v1.EstafetteReleaseEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.manifest.v1.EstafetteReleaseEvent}
 */
proto.manifest.v1.EstafetteReleaseEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReleaseVersion(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepoSource(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepoOwner(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepoName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTarget(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.manifest.v1.EstafetteReleaseEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.manifest.v1.EstafetteReleaseEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.manifest.v1.EstafetteReleaseEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manifest.v1.EstafetteReleaseEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReleaseVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRepoSource();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRepoOwner();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRepoName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTarget();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getEvent();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string release_version = 1;
 * @return {string}
 */
proto.manifest.v1.EstafetteReleaseEvent.prototype.getReleaseVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.manifest.v1.EstafetteReleaseEvent.prototype.setReleaseVersion = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string repo_source = 2;
 * @return {string}
 */
proto.manifest.v1.EstafetteReleaseEvent.prototype.getRepoSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.manifest.v1.EstafetteReleaseEvent.prototype.setRepoSource = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string repo_owner = 3;
 * @return {string}
 */
proto.manifest.v1.EstafetteReleaseEvent.prototype.getRepoOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.manifest.v1.EstafetteReleaseEvent.prototype.setRepoOwner = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string repo_name = 4;
 * @return {string}
 */
proto.manifest.v1.EstafetteReleaseEvent.prototype.getRepoName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.manifest.v1.EstafetteReleaseEvent.prototype.setRepoName = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string target = 5;
 * @return {string}
 */
proto.manifest.v1.EstafetteReleaseEvent.prototype.getTarget = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.manifest.v1.EstafetteReleaseEvent.prototype.setTarget = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string status = 6;
 * @return {string}
 */
proto.manifest.v1.EstafetteReleaseEvent.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.manifest.v1.EstafetteReleaseEvent.prototype.setStatus = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string event = 7;
 * @return {string}
 */
proto.manifest.v1.EstafetteReleaseEvent.prototype.getEvent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.manifest.v1.EstafetteReleaseEvent.prototype.setEvent = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


