/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.manifest.v1.EstafetteVersion');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.manifest.v1.EstafetteCustomVersion');
goog.require('proto.manifest.v1.EstafetteSemverVersion');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.manifest.v1.EstafetteVersion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.manifest.v1.EstafetteVersion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.manifest.v1.EstafetteVersion.displayName = 'proto.manifest.v1.EstafetteVersion';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.manifest.v1.EstafetteVersion.prototype.toObject = function(opt_includeInstance) {
  return proto.manifest.v1.EstafetteVersion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.manifest.v1.EstafetteVersion} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manifest.v1.EstafetteVersion.toObject = function(includeInstance, msg) {
  var f, obj = {
    semver: (f = msg.getSemver()) && proto.manifest.v1.EstafetteSemverVersion.toObject(includeInstance, f),
    custom: (f = msg.getCustom()) && proto.manifest.v1.EstafetteCustomVersion.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.manifest.v1.EstafetteVersion}
 */
proto.manifest.v1.EstafetteVersion.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.manifest.v1.EstafetteVersion;
  return proto.manifest.v1.EstafetteVersion.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.manifest.v1.EstafetteVersion} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.manifest.v1.EstafetteVersion}
 */
proto.manifest.v1.EstafetteVersion.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.manifest.v1.EstafetteSemverVersion;
      reader.readMessage(value,proto.manifest.v1.EstafetteSemverVersion.deserializeBinaryFromReader);
      msg.setSemver(value);
      break;
    case 2:
      var value = new proto.manifest.v1.EstafetteCustomVersion;
      reader.readMessage(value,proto.manifest.v1.EstafetteCustomVersion.deserializeBinaryFromReader);
      msg.setCustom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.manifest.v1.EstafetteVersion.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.manifest.v1.EstafetteVersion.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.manifest.v1.EstafetteVersion} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manifest.v1.EstafetteVersion.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSemver();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.manifest.v1.EstafetteSemverVersion.serializeBinaryToWriter
    );
  }
  f = message.getCustom();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.manifest.v1.EstafetteCustomVersion.serializeBinaryToWriter
    );
  }
};


/**
 * optional EstafetteSemverVersion semver = 1;
 * @return {?proto.manifest.v1.EstafetteSemverVersion}
 */
proto.manifest.v1.EstafetteVersion.prototype.getSemver = function() {
  return /** @type{?proto.manifest.v1.EstafetteSemverVersion} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteSemverVersion, 1));
};


/** @param {?proto.manifest.v1.EstafetteSemverVersion|undefined} value */
proto.manifest.v1.EstafetteVersion.prototype.setSemver = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.manifest.v1.EstafetteVersion.prototype.clearSemver = function() {
  this.setSemver(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteVersion.prototype.hasSemver = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional EstafetteCustomVersion custom = 2;
 * @return {?proto.manifest.v1.EstafetteCustomVersion}
 */
proto.manifest.v1.EstafetteVersion.prototype.getCustom = function() {
  return /** @type{?proto.manifest.v1.EstafetteCustomVersion} */ (
    jspb.Message.getWrapperField(this, proto.manifest.v1.EstafetteCustomVersion, 2));
};


/** @param {?proto.manifest.v1.EstafetteCustomVersion|undefined} value */
proto.manifest.v1.EstafetteVersion.prototype.setCustom = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.manifest.v1.EstafetteVersion.prototype.clearCustom = function() {
  this.setCustom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.manifest.v1.EstafetteVersion.prototype.hasCustom = function() {
  return jspb.Message.getField(this, 2) != null;
};


