/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.manifest.v1.EstafetteRelease');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.manifest.v1.EstafetteReleaseAction');
goog.require('proto.manifest.v1.EstafetteStage');
goog.require('proto.manifest.v1.EstafetteTrigger');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.manifest.v1.EstafetteRelease = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.manifest.v1.EstafetteRelease.repeatedFields_, null);
};
goog.inherits(proto.manifest.v1.EstafetteRelease, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.manifest.v1.EstafetteRelease.displayName = 'proto.manifest.v1.EstafetteRelease';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.manifest.v1.EstafetteRelease.repeatedFields_ = [3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.manifest.v1.EstafetteRelease.prototype.toObject = function(opt_includeInstance) {
  return proto.manifest.v1.EstafetteRelease.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.manifest.v1.EstafetteRelease} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manifest.v1.EstafetteRelease.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cloneRepository: jspb.Message.getFieldWithDefault(msg, 2, false),
    actionsList: jspb.Message.toObjectList(msg.getActionsList(),
    proto.manifest.v1.EstafetteReleaseAction.toObject, includeInstance),
    triggersList: jspb.Message.toObjectList(msg.getTriggersList(),
    proto.manifest.v1.EstafetteTrigger.toObject, includeInstance),
    stagesList: jspb.Message.toObjectList(msg.getStagesList(),
    proto.manifest.v1.EstafetteStage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.manifest.v1.EstafetteRelease}
 */
proto.manifest.v1.EstafetteRelease.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.manifest.v1.EstafetteRelease;
  return proto.manifest.v1.EstafetteRelease.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.manifest.v1.EstafetteRelease} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.manifest.v1.EstafetteRelease}
 */
proto.manifest.v1.EstafetteRelease.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCloneRepository(value);
      break;
    case 3:
      var value = new proto.manifest.v1.EstafetteReleaseAction;
      reader.readMessage(value,proto.manifest.v1.EstafetteReleaseAction.deserializeBinaryFromReader);
      msg.addActions(value);
      break;
    case 4:
      var value = new proto.manifest.v1.EstafetteTrigger;
      reader.readMessage(value,proto.manifest.v1.EstafetteTrigger.deserializeBinaryFromReader);
      msg.addTriggers(value);
      break;
    case 5:
      var value = new proto.manifest.v1.EstafetteStage;
      reader.readMessage(value,proto.manifest.v1.EstafetteStage.deserializeBinaryFromReader);
      msg.addStages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.manifest.v1.EstafetteRelease.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.manifest.v1.EstafetteRelease.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.manifest.v1.EstafetteRelease} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manifest.v1.EstafetteRelease.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCloneRepository();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getActionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.manifest.v1.EstafetteReleaseAction.serializeBinaryToWriter
    );
  }
  f = message.getTriggersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.manifest.v1.EstafetteTrigger.serializeBinaryToWriter
    );
  }
  f = message.getStagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.manifest.v1.EstafetteStage.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.manifest.v1.EstafetteRelease.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.manifest.v1.EstafetteRelease.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool clone_repository = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.manifest.v1.EstafetteRelease.prototype.getCloneRepository = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.manifest.v1.EstafetteRelease.prototype.setCloneRepository = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * repeated EstafetteReleaseAction actions = 3;
 * @return {!Array<!proto.manifest.v1.EstafetteReleaseAction>}
 */
proto.manifest.v1.EstafetteRelease.prototype.getActionsList = function() {
  return /** @type{!Array<!proto.manifest.v1.EstafetteReleaseAction>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.manifest.v1.EstafetteReleaseAction, 3));
};


/** @param {!Array<!proto.manifest.v1.EstafetteReleaseAction>} value */
proto.manifest.v1.EstafetteRelease.prototype.setActionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.manifest.v1.EstafetteReleaseAction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.manifest.v1.EstafetteReleaseAction}
 */
proto.manifest.v1.EstafetteRelease.prototype.addActions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.manifest.v1.EstafetteReleaseAction, opt_index);
};


proto.manifest.v1.EstafetteRelease.prototype.clearActionsList = function() {
  this.setActionsList([]);
};


/**
 * repeated EstafetteTrigger triggers = 4;
 * @return {!Array<!proto.manifest.v1.EstafetteTrigger>}
 */
proto.manifest.v1.EstafetteRelease.prototype.getTriggersList = function() {
  return /** @type{!Array<!proto.manifest.v1.EstafetteTrigger>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.manifest.v1.EstafetteTrigger, 4));
};


/** @param {!Array<!proto.manifest.v1.EstafetteTrigger>} value */
proto.manifest.v1.EstafetteRelease.prototype.setTriggersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.manifest.v1.EstafetteTrigger=} opt_value
 * @param {number=} opt_index
 * @return {!proto.manifest.v1.EstafetteTrigger}
 */
proto.manifest.v1.EstafetteRelease.prototype.addTriggers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.manifest.v1.EstafetteTrigger, opt_index);
};


proto.manifest.v1.EstafetteRelease.prototype.clearTriggersList = function() {
  this.setTriggersList([]);
};


/**
 * repeated EstafetteStage stages = 5;
 * @return {!Array<!proto.manifest.v1.EstafetteStage>}
 */
proto.manifest.v1.EstafetteRelease.prototype.getStagesList = function() {
  return /** @type{!Array<!proto.manifest.v1.EstafetteStage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.manifest.v1.EstafetteStage, 5));
};


/** @param {!Array<!proto.manifest.v1.EstafetteStage>} value */
proto.manifest.v1.EstafetteRelease.prototype.setStagesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.manifest.v1.EstafetteStage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.manifest.v1.EstafetteStage}
 */
proto.manifest.v1.EstafetteRelease.prototype.addStages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.manifest.v1.EstafetteStage, opt_index);
};


proto.manifest.v1.EstafetteRelease.prototype.clearStagesList = function() {
  this.setStagesList([]);
};


