/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.contracts.v1.Release');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.Duration');
goog.require('proto.google.protobuf.Timestamp');
goog.require('proto.manifest.v1.EstafetteEvent');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contracts.v1.Release = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.contracts.v1.Release.repeatedFields_, null);
};
goog.inherits(proto.contracts.v1.Release, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.contracts.v1.Release.displayName = 'proto.contracts.v1.Release';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.contracts.v1.Release.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contracts.v1.Release.prototype.toObject = function(opt_includeInstance) {
  return proto.contracts.v1.Release.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contracts.v1.Release} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.Release.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    action: jspb.Message.getFieldWithDefault(msg, 2, ""),
    id: jspb.Message.getFieldWithDefault(msg, 3, ""),
    repoSource: jspb.Message.getFieldWithDefault(msg, 4, ""),
    repoOwner: jspb.Message.getFieldWithDefault(msg, 5, ""),
    releaseVersion: jspb.Message.getFieldWithDefault(msg, 6, ""),
    releaseStatus: jspb.Message.getFieldWithDefault(msg, 7, ""),
    eventsList: jspb.Message.toObjectList(msg.getEventsList(),
    proto.manifest.v1.EstafetteEvent.toObject, includeInstance),
    insertedAt: (f = msg.getInsertedAt()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    duration: (f = msg.getDuration()) && proto.google.protobuf.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contracts.v1.Release}
 */
proto.contracts.v1.Release.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contracts.v1.Release;
  return proto.contracts.v1.Release.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contracts.v1.Release} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contracts.v1.Release}
 */
proto.contracts.v1.Release.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepoSource(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepoOwner(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setReleaseVersion(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setReleaseStatus(value);
      break;
    case 8:
      var value = new proto.manifest.v1.EstafetteEvent;
      reader.readMessage(value,proto.manifest.v1.EstafetteEvent.deserializeBinaryFromReader);
      msg.addEvents(value);
      break;
    case 9:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setInsertedAt(value);
      break;
    case 10:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 11:
      var value = new proto.google.protobuf.Duration;
      reader.readMessage(value,proto.google.protobuf.Duration.deserializeBinaryFromReader);
      msg.setDuration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contracts.v1.Release.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contracts.v1.Release.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contracts.v1.Release} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.Release.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAction();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRepoSource();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRepoOwner();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getReleaseVersion();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getReleaseStatus();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getEventsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.manifest.v1.EstafetteEvent.serializeBinaryToWriter
    );
  }
  f = message.getInsertedAt();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDuration();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.google.protobuf.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.contracts.v1.Release.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.contracts.v1.Release.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string action = 2;
 * @return {string}
 */
proto.contracts.v1.Release.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.contracts.v1.Release.prototype.setAction = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string id = 3;
 * @return {string}
 */
proto.contracts.v1.Release.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.contracts.v1.Release.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string repo_source = 4;
 * @return {string}
 */
proto.contracts.v1.Release.prototype.getRepoSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.contracts.v1.Release.prototype.setRepoSource = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string repo_owner = 5;
 * @return {string}
 */
proto.contracts.v1.Release.prototype.getRepoOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.contracts.v1.Release.prototype.setRepoOwner = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string release_version = 6;
 * @return {string}
 */
proto.contracts.v1.Release.prototype.getReleaseVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.contracts.v1.Release.prototype.setReleaseVersion = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string release_status = 7;
 * @return {string}
 */
proto.contracts.v1.Release.prototype.getReleaseStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.contracts.v1.Release.prototype.setReleaseStatus = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated manifest.v1.EstafetteEvent events = 8;
 * @return {!Array<!proto.manifest.v1.EstafetteEvent>}
 */
proto.contracts.v1.Release.prototype.getEventsList = function() {
  return /** @type{!Array<!proto.manifest.v1.EstafetteEvent>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.manifest.v1.EstafetteEvent, 8));
};


/** @param {!Array<!proto.manifest.v1.EstafetteEvent>} value */
proto.contracts.v1.Release.prototype.setEventsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.manifest.v1.EstafetteEvent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.manifest.v1.EstafetteEvent}
 */
proto.contracts.v1.Release.prototype.addEvents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.manifest.v1.EstafetteEvent, opt_index);
};


proto.contracts.v1.Release.prototype.clearEventsList = function() {
  this.setEventsList([]);
};


/**
 * optional google.protobuf.Timestamp inserted_at = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.contracts.v1.Release.prototype.getInsertedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.contracts.v1.Release.prototype.setInsertedAt = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.contracts.v1.Release.prototype.clearInsertedAt = function() {
  this.setInsertedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.Release.prototype.hasInsertedAt = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.contracts.v1.Release.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 10));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.contracts.v1.Release.prototype.setUpdatedAt = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.contracts.v1.Release.prototype.clearUpdatedAt = function() {
  this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.Release.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional google.protobuf.Duration duration = 11;
 * @return {?proto.google.protobuf.Duration}
 */
proto.contracts.v1.Release.prototype.getDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Duration, 11));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.contracts.v1.Release.prototype.setDuration = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.contracts.v1.Release.prototype.clearDuration = function() {
  this.setDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.Release.prototype.hasDuration = function() {
  return jspb.Message.getField(this, 11) != null;
};


