/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.contracts.v1.ReleaseLog');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.contracts.v1.BuildLogStep');
goog.require('proto.google.protobuf.Timestamp');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contracts.v1.ReleaseLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.contracts.v1.ReleaseLog.repeatedFields_, null);
};
goog.inherits(proto.contracts.v1.ReleaseLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.contracts.v1.ReleaseLog.displayName = 'proto.contracts.v1.ReleaseLog';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.contracts.v1.ReleaseLog.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contracts.v1.ReleaseLog.prototype.toObject = function(opt_includeInstance) {
  return proto.contracts.v1.ReleaseLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contracts.v1.ReleaseLog} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.ReleaseLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    repoSource: jspb.Message.getFieldWithDefault(msg, 2, ""),
    repoOwner: jspb.Message.getFieldWithDefault(msg, 3, ""),
    repoName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    releaseId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    stepsList: jspb.Message.toObjectList(msg.getStepsList(),
    proto.contracts.v1.BuildLogStep.toObject, includeInstance),
    insertedAt: (f = msg.getInsertedAt()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contracts.v1.ReleaseLog}
 */
proto.contracts.v1.ReleaseLog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contracts.v1.ReleaseLog;
  return proto.contracts.v1.ReleaseLog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contracts.v1.ReleaseLog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contracts.v1.ReleaseLog}
 */
proto.contracts.v1.ReleaseLog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepoSource(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepoOwner(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepoName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setReleaseId(value);
      break;
    case 6:
      var value = new proto.contracts.v1.BuildLogStep;
      reader.readMessage(value,proto.contracts.v1.BuildLogStep.deserializeBinaryFromReader);
      msg.addSteps(value);
      break;
    case 7:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setInsertedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contracts.v1.ReleaseLog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contracts.v1.ReleaseLog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contracts.v1.ReleaseLog} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.ReleaseLog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRepoSource();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRepoOwner();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRepoName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getReleaseId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getStepsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.contracts.v1.BuildLogStep.serializeBinaryToWriter
    );
  }
  f = message.getInsertedAt();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.contracts.v1.ReleaseLog.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.contracts.v1.ReleaseLog.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string repo_source = 2;
 * @return {string}
 */
proto.contracts.v1.ReleaseLog.prototype.getRepoSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.contracts.v1.ReleaseLog.prototype.setRepoSource = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string repo_owner = 3;
 * @return {string}
 */
proto.contracts.v1.ReleaseLog.prototype.getRepoOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.contracts.v1.ReleaseLog.prototype.setRepoOwner = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string repo_name = 4;
 * @return {string}
 */
proto.contracts.v1.ReleaseLog.prototype.getRepoName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.contracts.v1.ReleaseLog.prototype.setRepoName = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string release_id = 5;
 * @return {string}
 */
proto.contracts.v1.ReleaseLog.prototype.getReleaseId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.contracts.v1.ReleaseLog.prototype.setReleaseId = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated BuildLogStep steps = 6;
 * @return {!Array<!proto.contracts.v1.BuildLogStep>}
 */
proto.contracts.v1.ReleaseLog.prototype.getStepsList = function() {
  return /** @type{!Array<!proto.contracts.v1.BuildLogStep>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.contracts.v1.BuildLogStep, 6));
};


/** @param {!Array<!proto.contracts.v1.BuildLogStep>} value */
proto.contracts.v1.ReleaseLog.prototype.setStepsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.contracts.v1.BuildLogStep=} opt_value
 * @param {number=} opt_index
 * @return {!proto.contracts.v1.BuildLogStep}
 */
proto.contracts.v1.ReleaseLog.prototype.addSteps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.contracts.v1.BuildLogStep, opt_index);
};


proto.contracts.v1.ReleaseLog.prototype.clearStepsList = function() {
  this.setStepsList([]);
};


/**
 * optional google.protobuf.Timestamp inserted_at = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.contracts.v1.ReleaseLog.prototype.getInsertedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 7));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.contracts.v1.ReleaseLog.prototype.setInsertedAt = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.contracts.v1.ReleaseLog.prototype.clearInsertedAt = function() {
  this.setInsertedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.ReleaseLog.prototype.hasInsertedAt = function() {
  return jspb.Message.getField(this, 7) != null;
};


