/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.contracts.v1.ReleaseParamsConfig');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contracts.v1.ReleaseParamsConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contracts.v1.ReleaseParamsConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.contracts.v1.ReleaseParamsConfig.displayName = 'proto.contracts.v1.ReleaseParamsConfig';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contracts.v1.ReleaseParamsConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.contracts.v1.ReleaseParamsConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contracts.v1.ReleaseParamsConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.ReleaseParamsConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    releaseName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    releaseId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    releaseAction: jspb.Message.getFieldWithDefault(msg, 3, ""),
    triggeredBy: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contracts.v1.ReleaseParamsConfig}
 */
proto.contracts.v1.ReleaseParamsConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contracts.v1.ReleaseParamsConfig;
  return proto.contracts.v1.ReleaseParamsConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contracts.v1.ReleaseParamsConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contracts.v1.ReleaseParamsConfig}
 */
proto.contracts.v1.ReleaseParamsConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReleaseName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setReleaseId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setReleaseAction(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTriggeredBy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contracts.v1.ReleaseParamsConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contracts.v1.ReleaseParamsConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contracts.v1.ReleaseParamsConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.ReleaseParamsConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReleaseName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReleaseId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getReleaseAction();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTriggeredBy();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string release_name = 1;
 * @return {string}
 */
proto.contracts.v1.ReleaseParamsConfig.prototype.getReleaseName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.contracts.v1.ReleaseParamsConfig.prototype.setReleaseName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 release_id = 2;
 * @return {number}
 */
proto.contracts.v1.ReleaseParamsConfig.prototype.getReleaseId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.contracts.v1.ReleaseParamsConfig.prototype.setReleaseId = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string release_action = 3;
 * @return {string}
 */
proto.contracts.v1.ReleaseParamsConfig.prototype.getReleaseAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.contracts.v1.ReleaseParamsConfig.prototype.setReleaseAction = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string triggered_by = 4;
 * @return {string}
 */
proto.contracts.v1.ReleaseParamsConfig.prototype.getTriggeredBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.contracts.v1.ReleaseParamsConfig.prototype.setTriggeredBy = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


