/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.contracts.v1.TailLogLine');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.contracts.v1.BuildLogLine');
goog.require('proto.contracts.v1.BuildLogStepDockerImage');
goog.require('proto.google.protobuf.Duration');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contracts.v1.TailLogLine = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contracts.v1.TailLogLine, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.contracts.v1.TailLogLine.displayName = 'proto.contracts.v1.TailLogLine';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contracts.v1.TailLogLine.prototype.toObject = function(opt_includeInstance) {
  return proto.contracts.v1.TailLogLine.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contracts.v1.TailLogLine} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.TailLogLine.toObject = function(includeInstance, msg) {
  var f, obj = {
    step: jspb.Message.getFieldWithDefault(msg, 1, ""),
    logLine: (f = msg.getLogLine()) && proto.contracts.v1.BuildLogLine.toObject(includeInstance, f),
    image: (f = msg.getImage()) && proto.contracts.v1.BuildLogStepDockerImage.toObject(includeInstance, f),
    duration: (f = msg.getDuration()) && proto.google.protobuf.Duration.toObject(includeInstance, f),
    exitCode: jspb.Message.getFieldWithDefault(msg, 5, 0),
    status: jspb.Message.getFieldWithDefault(msg, 6, ""),
    autoInjected: jspb.Message.getFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contracts.v1.TailLogLine}
 */
proto.contracts.v1.TailLogLine.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contracts.v1.TailLogLine;
  return proto.contracts.v1.TailLogLine.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contracts.v1.TailLogLine} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contracts.v1.TailLogLine}
 */
proto.contracts.v1.TailLogLine.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStep(value);
      break;
    case 2:
      var value = new proto.contracts.v1.BuildLogLine;
      reader.readMessage(value,proto.contracts.v1.BuildLogLine.deserializeBinaryFromReader);
      msg.setLogLine(value);
      break;
    case 3:
      var value = new proto.contracts.v1.BuildLogStepDockerImage;
      reader.readMessage(value,proto.contracts.v1.BuildLogStepDockerImage.deserializeBinaryFromReader);
      msg.setImage(value);
      break;
    case 4:
      var value = new proto.google.protobuf.Duration;
      reader.readMessage(value,proto.google.protobuf.Duration.deserializeBinaryFromReader);
      msg.setDuration(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExitCode(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutoInjected(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contracts.v1.TailLogLine.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contracts.v1.TailLogLine.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contracts.v1.TailLogLine} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.TailLogLine.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStep();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLogLine();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.contracts.v1.BuildLogLine.serializeBinaryToWriter
    );
  }
  f = message.getImage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.contracts.v1.BuildLogStepDockerImage.serializeBinaryToWriter
    );
  }
  f = message.getDuration();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.google.protobuf.Duration.serializeBinaryToWriter
    );
  }
  f = message.getExitCode();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getAutoInjected();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional string step = 1;
 * @return {string}
 */
proto.contracts.v1.TailLogLine.prototype.getStep = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.contracts.v1.TailLogLine.prototype.setStep = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional BuildLogLine log_line = 2;
 * @return {?proto.contracts.v1.BuildLogLine}
 */
proto.contracts.v1.TailLogLine.prototype.getLogLine = function() {
  return /** @type{?proto.contracts.v1.BuildLogLine} */ (
    jspb.Message.getWrapperField(this, proto.contracts.v1.BuildLogLine, 2));
};


/** @param {?proto.contracts.v1.BuildLogLine|undefined} value */
proto.contracts.v1.TailLogLine.prototype.setLogLine = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.contracts.v1.TailLogLine.prototype.clearLogLine = function() {
  this.setLogLine(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.TailLogLine.prototype.hasLogLine = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional BuildLogStepDockerImage image = 3;
 * @return {?proto.contracts.v1.BuildLogStepDockerImage}
 */
proto.contracts.v1.TailLogLine.prototype.getImage = function() {
  return /** @type{?proto.contracts.v1.BuildLogStepDockerImage} */ (
    jspb.Message.getWrapperField(this, proto.contracts.v1.BuildLogStepDockerImage, 3));
};


/** @param {?proto.contracts.v1.BuildLogStepDockerImage|undefined} value */
proto.contracts.v1.TailLogLine.prototype.setImage = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.contracts.v1.TailLogLine.prototype.clearImage = function() {
  this.setImage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.TailLogLine.prototype.hasImage = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Duration duration = 4;
 * @return {?proto.google.protobuf.Duration}
 */
proto.contracts.v1.TailLogLine.prototype.getDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Duration, 4));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.contracts.v1.TailLogLine.prototype.setDuration = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.contracts.v1.TailLogLine.prototype.clearDuration = function() {
  this.setDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.contracts.v1.TailLogLine.prototype.hasDuration = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int64 exit_code = 5;
 * @return {number}
 */
proto.contracts.v1.TailLogLine.prototype.getExitCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.contracts.v1.TailLogLine.prototype.setExitCode = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string status = 6;
 * @return {string}
 */
proto.contracts.v1.TailLogLine.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.contracts.v1.TailLogLine.prototype.setStatus = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional bool auto_injected = 7;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.contracts.v1.TailLogLine.prototype.getAutoInjected = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 7, false));
};


/** @param {boolean} value */
proto.contracts.v1.TailLogLine.prototype.setAutoInjected = function(value) {
  jspb.Message.setProto3BooleanField(this, 7, value);
};


