/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.contracts.v1.TrustedImageConfig');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contracts.v1.TrustedImageConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.contracts.v1.TrustedImageConfig.repeatedFields_, null);
};
goog.inherits(proto.contracts.v1.TrustedImageConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.contracts.v1.TrustedImageConfig.displayName = 'proto.contracts.v1.TrustedImageConfig';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.contracts.v1.TrustedImageConfig.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contracts.v1.TrustedImageConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.contracts.v1.TrustedImageConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contracts.v1.TrustedImageConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.TrustedImageConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    imagePath: jspb.Message.getFieldWithDefault(msg, 1, ""),
    runPrivileged: jspb.Message.getFieldWithDefault(msg, 2, false),
    runDocker: jspb.Message.getFieldWithDefault(msg, 3, false),
    allowCommands: jspb.Message.getFieldWithDefault(msg, 4, false),
    injectedCredentialTypesList: jspb.Message.getRepeatedField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contracts.v1.TrustedImageConfig}
 */
proto.contracts.v1.TrustedImageConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contracts.v1.TrustedImageConfig;
  return proto.contracts.v1.TrustedImageConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contracts.v1.TrustedImageConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contracts.v1.TrustedImageConfig}
 */
proto.contracts.v1.TrustedImageConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setImagePath(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRunPrivileged(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRunDocker(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowCommands(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addInjectedCredentialTypes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contracts.v1.TrustedImageConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contracts.v1.TrustedImageConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contracts.v1.TrustedImageConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contracts.v1.TrustedImageConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getImagePath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRunPrivileged();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getRunDocker();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getAllowCommands();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getInjectedCredentialTypesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * optional string image_path = 1;
 * @return {string}
 */
proto.contracts.v1.TrustedImageConfig.prototype.getImagePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.contracts.v1.TrustedImageConfig.prototype.setImagePath = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool run_privileged = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.contracts.v1.TrustedImageConfig.prototype.getRunPrivileged = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.contracts.v1.TrustedImageConfig.prototype.setRunPrivileged = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool run_docker = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.contracts.v1.TrustedImageConfig.prototype.getRunDocker = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.contracts.v1.TrustedImageConfig.prototype.setRunDocker = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool allow_commands = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.contracts.v1.TrustedImageConfig.prototype.getAllowCommands = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.contracts.v1.TrustedImageConfig.prototype.setAllowCommands = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * repeated string injected_credential_types = 5;
 * @return {!Array<string>}
 */
proto.contracts.v1.TrustedImageConfig.prototype.getInjectedCredentialTypesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.contracts.v1.TrustedImageConfig.prototype.setInjectedCredentialTypesList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.contracts.v1.TrustedImageConfig.prototype.addInjectedCredentialTypes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.contracts.v1.TrustedImageConfig.prototype.clearInjectedCredentialTypesList = function() {
  this.setInjectedCredentialTypesList([]);
};


